services:
  s3s:
    build: .
    image: s3s-custom:latest
    container_name: s3s-app
    volumes:
      - .:/app
    stdin_open: true
    tty: true

  db-viewer:
    image: coleifer/sqlite-web
    container_name: s3s-db-viewer
    ports:
      - "8080:8080"
    volumes:
      - .:/data
    command: sqlite_web -H 0.0.0.0 /data/splatoon3_battles.db

  dashboard:
    build: .
    container_name: s3s-dashboard
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    command: ["streamlit", "run", "dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]